classApp/classApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import discuss

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('', include('discuss.urls')),
    path('',include('quiz.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classApp/discuss/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url

app_name = 'discuss'

urlpatterns = [
    path('create-post/', views.create_post, name='add-post'),
    path('forum/', views.forum_home, name='forum-home'),
    path('post/<post_id>', views.post_detail, name='post-detail'),
    path('add-reply/<post_id>', views.add_reply, name='add-reply'),
]

classApp/quiz/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url

app_name = 'quiz'

urlpatterns = [
    path('create-quiz/', views.create_quiz, name='create-quiz'),
    path('quiz-home/', views.quiz_home, name='quiz-home'),
    path('quiz/<quiz_id>', views.quiz_detail, name='quiz-detail'),
    path('add-ques/<quiz_id>', views.add_question, name='add-question'),
    path('attempt-quiz/<quiz_id>', views.attempt_quiz, name='attempt-quiz'),
    # path('view-result/<quiz_id>', views.attempt_quiz, name='view-result'),
]

classApp/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url

app_name = 'users'

urlpatterns = [
    path("", views.index_view, name='home'),
    path('student_register/',views.stud_register.as_view(),name='student_register'),
    path('teacher_register/',views.teacher_register.as_view(),name='teacher_register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('student-profile/', views.student_profile, name='student-profile'),
    path('teacher-profile/', views.teacher_profile, name='teacher-profile'),
    path('quiz-responses/<quiz_id>', views.quiz_responses, name='quiz_responses'),
    path('view-response-sheet/<resp_id>', views.view_response_sheet, name='view_response_sheet'),
]

classApp/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse

BRANCH_CHOICES = (
    ('CSE', 'Computer Science'),
    ('ECE', 'Electronics'),
    ('BIO', 'Bio-medical'),
    ('DSE','Datascience'),
    ('GEN','Generic')
)

class User(AbstractUser):
    email = models.EmailField()
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    stud_name = models.CharField(max_length=30)
    email = models.EmailField(default="")
    branch = models.CharField(choices=BRANCH_CHOICES, max_length =3, default = 'GEN')
    student_profile_pic = models.ImageField(default='img.png', upload_to='profile_pics', blank=True)

    def get_absolute_url(self):
        return reverse('/student', kwargs={'pk': self.pk})

    def __str__(self):
        return self.user.username

class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,primary_key=True)
    teacher_name = models.CharField(max_length=30)
    contact_number = models.CharField(max_length=10)
    email = models.EmailField(default = "")
    teacher_profile_pic = models.ImageField(default='img.png',upload_to = 'profile_pics',blank=True)
    #qualif = models.TextField()
    designation = models.CharField(max_length=300)
    branch = models.CharField(choices=BRANCH_CHOICES, max_length =3, default = 'GEN')
    def get_absolute_url(self):
        return reverse('/teacher',kwargs={'pk':self.pk})


    def __str__(self):
        return self.teacher_name

classApp/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.db import transaction
from .models import *

CHOICES = [
    ('CSE', 'Computer Science'),
    ('ECE', 'Electronics'),
    ('BIO', 'Bio-medical'),
    ('DSE','Datascience'),
    ('GEN','Generic')
]

class StudentRegistrationForm(UserCreationForm):
    email = forms.CharField(required=True)
    stud_name = forms.CharField(required=True)
    #branch = forms.Select(choices=CHOICES)
    branch = forms.CharField(label='Branch', widget=forms.Select(choices=CHOICES))
    class Meta(UserCreationForm.Meta):
        model = User
    
    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.email=self.cleaned_data.get('email')
        user.save()
        student = Student.objects.create(user=user)
        student.email = self.cleaned_data.get('email')
        student.stud_name = self.cleaned_data.get('stud_name')
        student.branch = self.cleaned_data.get('branch')
        student.save()
        return user


class TeacherRegistrationForm(UserCreationForm):
    email = forms.CharField(required=True)
    teacher_name = forms.CharField(required=True)
    contact_number = forms.CharField(required=True)
    designation = forms.CharField(required=True)
    branch = forms.CharField(label='Branch', widget=forms.Select(choices=CHOICES))
    class Meta(UserCreationForm.Meta):
        model = User  

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_teacher=True
        user.email=self.cleaned_data.get('email')
        user.save()
        teacher = Teacher.objects.create(user=user)
        teacher.teacher_name=self.cleaned_data.get('teacher_name')
        teacher.designation = self.cleaned_data.get('designation')
        teacher.contact_number=self.cleaned_data.get('contact_number')
        teacher.branch = self.cleaned_data.get('branch')
        teacher.email=self.cleaned_data.get('email')
        teacher.save()
        return user 

classApp/users/views.py
from django.http.response import HttpResponse
from django.shortcuts import render,redirect, get_object_or_404, HttpResponseRedirect
from django.contrib.auth import login,logout,authenticate
from django.views.generic import CreateView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from datetime import datetime
from users.decorators import *
from .forms import *
from .models import *
from discuss.models import *
from quiz.models import * 

def index_view(request):
    return render(request, 'discuss/forum.html', context={'posts' : Post.objects.all()})
    #return render(request, 'users/home1.html')

class stud_register(CreateView):
    model = User
    form_class = StudentRegistrationForm
    template_name = 'users/student_register.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)
    def form_valid(self,form):
        user = form.save()
        login(self.request,user)
        return redirect('/')


class teacher_register(CreateView):
    model = User
    form_class = TeacherRegistrationForm
    template_name = 'users/teacher_register.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'teacher'
        return super().get_context_data(**kwargs)
    def form_valid(self,form):
        user = form.save()
        login(self.request,user)
        return redirect('/')

def login_view(request):
    if request.method=='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            if user is not None:
                login(request,user)
                return redirect('/')
            else:
                messages.error(request,"Invalid username or password")
        else:
                messages.error(request,"Invalid username or password")

    return render(request,'users/login.html',context={'form':AuthenticationForm()})

def logout_view(request):
    logout(request)
    return redirect('/')

@login_required
@student_required 
def student_profile(request):
    student = Student.objects.get(user = request.user)
    response_sheets = ResponseSheet.objects.filter(student=request.user)
    context = {
        "student" : student,
        "response_sheets" : list(response_sheets),
    }
    return render(request, 'users/student-profile.html', context)

@login_required
@teacher_required
def teacher_profile(request):
    teacher = Teacher.objects.get(user=request.user)
    quizzes = Quiz.objects.filter(author=request.user)
    context = {
        "teacher" : teacher,
        "quizzes" : list(quizzes),
    }
    return render(request, 'users/teacher-profile.html', context)

@login_required
@teacher_required
def quiz_responses(request, quiz_id):
    quiz = get_object_or_404(Quiz, id=quiz_id)
    response_qs = ResponseSheet.objects.filter(quiz=quiz)
    context = {
        "quiz" : quiz,
        "responses" : list(response_qs),
    }
    return render(request, 'users/quiz_responses.html', context)

@login_required
def view_response_sheet(request, resp_id):
    response_sheet = ResponseSheet.objects.get(id = resp_id)
    user = response_sheet.student
    responses = response_sheet.responses.all()
    context = {
        "student" : user,
        "responses" : responses,
    }
    return render(request, 'users/view_response_sheet.html', context)

classApp/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>

	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href=" {% static 'users/main1.css' %} ">    <!--linking our main.css file over here -->
	{% if title %}
	   <title>Django Blog - {{title}} </title>
	{% else %}
	   <title>Class room</title>
	{% endif %}

</head>
<body>

	<!--Navigation Bar Starts-->
	<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container">
      <a class="navbar-brand mr-4" href="#">Class room</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
          <a class="nav-item nav-link" href=" {% url 'users:home' %} ">Home</a>
          <a class="nav-item nav-link" href="#">About</a>
        </div>
        <!-- Navbar Right Side -->
        <div class="navbar-nav">

          {% if user.is_authenticated %}
                <!--<a class="nav-item nav-link" href="#">New Post</a>-->
                <a class="nav-item nav-link" href=" {% url 'users:logout' %} ">Logout</a>
                {%if request.user.is_student %}
                <a class="nav-item nav-link" href="{% url 'users:student-profile' %}">Profile</a>
                {% else %}
                <a class="nav-item nav-link" href="#">Profile</a>
                {% endif %}

          {% else %}

                <a class="nav-item nav-link" href=" {% url 'users:login' %} ">Login</a>
                <a class="nav-item nav-link" href=" {% url 'users:student_register' %} ">Student signup</a>
                <a class="nav-item nav-link" href=" {% url 'users:teacher_register' %} ">Teacher signup</a>

          {% endif %}
          
        </div>
      </div>
    </div>
    </nav> 
    </header>
    <!--Navigation Bar ends-->


    <!--block content (code copied from snippets) -->
	<main role="main" class="container">
  <div class="row">
    <div class="col-md-8">

      {% block content %}{% endblock content%}
      {% if messages %}                                             <!--code to print out the flash messages-->
      {% for message in messages %}
          <br><br><br><br>
           <div class="alert alert-{{ message.tags }}">
                {{ message }}
           </div>
      {% endfor %}
{% endif %}
    </div>
    <div class="col-md-4">
      <div class="content-section">
      	<br> <br> <br> <br>
        <h3>Our Sidebar</h3>
        <p class='text-muted'>You can put any information here you'd like.
          <ul class="list-group">
            <li class="list-group-item list-group-item-light">Latest Posts</li>
            <li class="list-group-item list-group-item-light">Announcements</li>
            <li class="list-group-item list-group-item-light">Calendars</li>
            <li class="list-group-item list-group-item-light">etc</li>
          </ul>
        </p>
      </div>
    </div>
  </div>
     </main>
    <!--Block content ends-->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

classApp/templates/users/login.html
{% extends 'discuss/basic.html' %}
{% load crispy_forms_tags %}
<!--{% block title %} Forum {% endblock %}
{% block homeactive %} active {% endblock homeactive %}-->
{% block content %}
<br><br>
<div id="login-box"; style="padding: 70px 0; text-align: center;">
    <div class="items">
      <h1>Log in</h1>   <br><br>

      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            {{ form|crispy }}        <!--Prints out the form that we've passed. as_p will render our form in paragraph tags-->
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Login</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need an account? <a class="ml-2" href="{% url 'users:student_register' %}">Sign Up Now</a>
        </small>
    </div>

</div>   
{% endblock content %}

classApp/templates/users/quiz_responses.html
{% extends 'discuss/basic.html' %}
{% load crispy_forms_tags %}
<!--{% block title %} Forum {% endblock %}
{% block homeactive %} active {% endblock homeactive %}-->
{% block content %}
<div class="container my-4">
<div class="jumbotron">
    <h1 class="display-4">{{quiz.name}} Results</h1>
    <!--<p class="lead">Welcome to our discussion forum. You can post your question or any related queries by simply clicking on the add post button. <br> Thankyou and Have a nice day!!</p>
    <hr class="my-4">
    <p>You can also reply to others post by clicking on their post and replying them.</p>
      <a class="btn btn-primary btn-lg" data-toggle="modal" href="{% url 'discuss:add-post' %}">Add post!</a>-->
    </div>

</div>

<!-- cards -->
<div class="container">
    <div class="container mx-auto mt-2">
      <div class="row">
  
        {% for response in responses %}
        <div class="col-md-4">
          <div class="card" style="width: 21rem;">
            <div class="card-body" >
              <h5 class="card-title" style="text-align: center;">{{response.student}}</h5>
              <br>
              <p class="card-text">Total score = {{response.score}}</p>
              <p class="card-text">Correct answers = {{response.correct}}</p>
              <p class="card-text">Wrong answers = {{response.wrong}}</p>
              <div class="card-footer d-flex flex-wrap justify-content-between align-items-center px-0 pt-1 pb-3">
                <a class="btn btn-primary btn-lg" data-toggle="modal" href="{{response.get_response_sheet_url}}">Response Sheet</a>                 
              </div>
              
              <br>
              <!-- <button data-bs-target="#exampleModal" data-bs-toggle="modal" data-time="{{i.time}}"
                data-questions="{{i.number_of_questions}}" data-name="{{i.name}}" data-id="{{i.id}}" id="btn"
                style="justify-content: center;" class="attempt btn mr-2 modal-button"><i class="fas fa-link"></i>Attempt
                Quiz</button> -->
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

{% endblock content %}

classApp/templates/users/student-profile.html
{% extends 'discuss/basic.html' %}
{% load crispy_forms_tags %}
<!--{% block title %} Forum {% endblock %}
{% block homeactive %} active {% endblock homeactive %}-->
{% block content %}
<div class="container my-4">
<div class="jumbotron">
    <h1 class="display-4">Hi {{request.user}}</h1>
    <!--<p class="lead">Welcome to our discussion forum. You can post your question or any related queries by simply clicking on the add post button. <br> Thankyou and Have a nice day!!</p>
    <hr class="my-4">
    <p>You can also reply to others post by clicking on their post and replying them.</p>
      <a class="btn btn-primary btn-lg" data-toggle="modal" href="{% url 'discuss:add-post' %}">Add post!</a>-->
    </div>

    <div class="container-fluid mt-10">
      <div class="row">
          <div class="col-md-12">
              <div class="card mb-4">
                  <div class="card-header">
                      <div class="media flex-wrap w-100 align-items-center"> 
                          email : {{student.email}} <br>

                </div>
              </div>
          </div>
      </div>
  </div>

</div>
<h2>Your performance reports</h2>
<!-- cards -->
<div class="container">
    <div class="container mx-auto mt-2">
      <div class="row">
  
        {% for response_sheet in response_sheets %}
        <div class="col-md-4">
          <div class="card" style="width: 21rem;">
            <div class="card-body" >
              <h5 class="card-title" style="text-align: center;">{{response_sheet.quiz.name}}</h5>
              <br>
              <p class="card-text">Total score = {{response_sheet.score}}</p>
              <p class="card-text">Correct answers = {{response_sheet.correct}}</p>
              <p class="card-text">Wrong answers = {{response_sheet.wrong}}</p>
              <div class="card-footer d-flex flex-wrap justify-content-between align-items-center px-0 pt-1 pb-3">
                <a class="btn btn-primary btn-lg" data-toggle="modal" href="{{response_sheet.get_response_sheet_url}}">Response Sheet</a>                 
              </div>
              
              <br>
              <!-- <button data-bs-target="#exampleModal" data-bs-toggle="modal" data-time="{{i.time}}"
                data-questions="{{i.number_of_questions}}" data-name="{{i.name}}" data-id="{{i.id}}" id="btn"
                style="justify-content: center;" class="attempt btn mr-2 modal-button"><i class="fas fa-link"></i>Attempt
                Quiz</button> -->
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

{% endblock content %}

classApp/templates/users/student-profile1.html
{% extends 'discuss/basic.html' %}
{% load crispy_forms_tags %}
<!--{% block title %} Forum {% endblock %}
{% block homeactive %} active {% endblock homeactive %}-->
{% block content %}
<div class="container my-4">
<div class="jumbotron">
    <h1 class="display-4">Hi {{request.user}}</h1>
    <!--<p class="lead">Welcome to our discussion forum. You can post your question or any related queries by simply clicking on the add post button. <br> Thankyou and Have a nice day!!</p>
    <hr class="my-4">
    <p>You can also reply to others post by clicking on their post and replying them.</p>
      <a class="btn btn-primary btn-lg" data-toggle="modal" href="{% url 'discuss:add-post' %}">Add post!</a>-->
    </div>

    <div class="container-fluid mt-10">
      <div class="row">
          <div class="col-md-12">
              <div class="card mb-4">
                  <div class="card-header">
                      <div class="media flex-wrap w-100 align-items-center"> 
                          email : {{student.email}} <br>

                </div>
              </div>
          </div>
      </div>
  </div>

</div>
<h2>Your performance reports</h2>
  
        {% for response_sheet in response_sheets %}
        <div class="col-md-4">
          <div class="card" style="width: 21rem;">
            <div class="card-body">
              <h5 class="card-title" style="text-align: center;">{{response_sheet.quiz.name}}</h5>
              <br>
              <p class="card-text">Total score = {{response_sheet.score}}</p>
              <p class="card-text">Correct answers = {{response_sheet.correct}}</p>
              <p class="card-text">Wrong answers = {{response_sheet.wrong}}</p>
              
              <br>
              <!-- <button data-bs-target="#exampleModal" data-bs-toggle="modal" data-time="{{i.time}}"
                data-questions="{{i.number_of_questions}}" data-name="{{i.name}}" data-id="{{i.id}}" id="btn"
                style="justify-content: center;" class="attempt btn mr-2 modal-button"><i class="fas fa-link"></i>Attempt
                Quiz</button> -->
            </div>
          </div>
        </div>
        {% endfor %}
<!--  
{% for reply in replies %}
<br>
<div class="container">
<div class="media">
    <img class="mr-3 rounded-circle" src="/media/{{reply.image}}" alt="." width="30px" height="30px">
    <div class="media-body">
      <h4 class="mt-0">{{reply.user}}	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;  <span><small style="font-size: 13px;">({{reply.timestamp}})</small></span></h4>   
      <h5>{{reply.reply_content}}</h5>
    </div>
  </div>
</div>
{% endfor %} -->
{% endblock content %}

classApp/templates/users/student_register.html
{% extends 'discuss/basic.html' %}
{% load crispy_forms_tags %}
<!--{% block title %} Forum {% endblock %}
{% block homeactive %} active {% endblock homeactive %}-->
{% block content %}
<br><br>
<div id="login-box"; style="padding: 70px 0; text-align: center;">
    <div class="items">
      <h1>Student Sign-up</h1>   <br><br>

      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            {{ form|crispy }}        <!--Prints out the form that we've passed. as_p will render our form in paragraph tags-->
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Register</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already have an account? <a class="ml-2" href="{% url 'users:login' %}">Login now!</a>
        </small>
    </div>

</div>   
{% endblock content %}

classApp/templates/users/teacher-profile.html
{% extends 'discuss/basic.html' %}
{% load crispy_forms_tags %}
<!--{% block title %} Forum {% endblock %}
{% block homeactive %} active {% endblock homeactive %}-->
{% block content %}
<div class="container my-4">
<div class="jumbotron">
    <h1 class="display-4">Hi {{request.user}}</h1>
    <!--<p class="lead">Welcome to our discussion forum. You can post your question or any related queries by simply clicking on the add post button. <br> Thankyou and Have a nice day!!</p>
    <hr class="my-4">
    <p>You can also reply to others post by clicking on their post and replying them.</p>
      <a class="btn btn-primary btn-lg" data-toggle="modal" href="{% url 'discuss:add-post' %}">Add post!</a>-->
    </div>

    <div class="container-fluid mt-10">
      <div class="row">
          <div class="col-md-12">
              <div class="card mb-4">
                  <div class="card-header">
                      <div class="media flex-wrap w-100 align-items-center"> 
                          email : {{teacher.email}} <br>
                          designation : {{teacher.designation}} <br>

                </div>
              </div>
          </div>
      </div>
  </div>

</div>
<h2>Quizzes Hosted</h2>
<!-- cards -->
<div class="container">
    <div class="container mx-auto mt-2">
      <div class="row">
  
        {% for quiz in quizzes %}
        <div class="col-md-4">
          <div class="card" style="width: 21rem;">
            <div class="card-body">
              <h5 class="card-title" style="text-align: center;">{{quiz.name}}</h5>
              <br>
              <p class="card-text">{{quiz.desc}}</p>
  
              <div class="card-footer d-flex flex-wrap justify-content-between align-items-center px-0 pt-1 pb-3"> 
                  <a class="btn btn-primary btn-lg" data-toggle="modal" href="#">View Responses</a>                 
              </div>
              <!-- <button data-bs-target="#exampleModal" data-bs-toggle="modal" data-time="{{i.time}}"
                data-questions="{{i.number_of_questions}}" data-name="{{i.name}}" data-id="{{i.id}}" id="btn"
                style="justify-content: center;" class="attempt btn mr-2 modal-button"><i class="fas fa-link"></i>Attempt
                Quiz</button> -->
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
<!--  
{% for reply in replies %}
<br>
<div class="container">
<div class="media">
    <img class="mr-3 rounded-circle" src="/media/{{reply.image}}" alt="." width="30px" height="30px">
    <div class="media-body">
      <h4 class="mt-0">{{reply.user}}	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;  <span><small style="font-size: 13px;">({{reply.timestamp}})</small></span></h4>   
      <h5>{{reply.reply_content}}</h5>
    </div>
  </div>
</div>
{% endfor %} -->
{% endblock content %}

classApp/templates/users/teacher_register.html
{% extends 'discuss/basic.html' %}
{% load crispy_forms_tags %}
<!--{% block title %} Forum {% endblock %}
{% block homeactive %} active {% endblock homeactive %}-->
{% block content %}
<br><br>
<div id="login-box"; style="padding: 70px 0; text-align: center;">
    <div class="items">
      <h1>Teacher Sign-up</h1>   <br><br>

      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            {{ form|crispy }}        <!--Prints out the form that we've passed. as_p will render our form in paragraph tags-->
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Register</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already have an account? <a class="ml-2" href="{% url 'users:login' %}">Login now!</a>
        </small>
    </div>

</div>   
{% endblock content %}

classApp/templates/users/view_response_sheet.html
{% extends 'discuss/basic.html' %}
{% load crispy_forms_tags %}
<!--{% block title %} Forum {% endblock %}
{% block homeactive %} active {% endblock homeactive %}-->
{% block content %}

<div class="container my-4">
    <div class="jumbotron">
        <h1 class="display-4">Response sheet of {{student}} </h1>
        <!--<p class="lead">Welcome to our discussion forum. You can post your question or any related queries by simply clicking on the add post button. <br> Thankyou and Have a nice day!!</p>
        <hr class="my-4">
        <p>You can also reply to others post by clicking on their post and replying them.</p>
          <a class="btn btn-primary btn-lg" data-toggle="modal" href="{% url 'discuss:add-post' %}">Add post!</a>-->
        </div>
    
    </div>
{% for response in responses %}
<div class="container"; style="padding: 70px 0;">
<div class="media">
    <div class="media-body">
        <h5>{{response.question.desc}}</h5>
        <ol>
            <li>{{response.question.choice1}}</li>
            <li>{{response.question.choice2}}</li>
            <li>{{response.question.choice3}}</li>
            <li>{{response.question.choice4}}</li>
        </ol>
        Response recorded: {{response.choice_picked}} <br>
        Correct answer:  {{response.question.ans}} 
    </div>
  </div>
</div>
{% endfor %}
{% endblock content %}