classApp/classApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import discuss

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('', include('discuss.urls')),
    path('',include('quiz.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classApp/discuss/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url

app_name = 'discuss'

urlpatterns = [
    path('create-post/', views.create_post, name='add-post'),
    path('forum/', views.forum_home, name='forum-home'),
    path('post/<post_id>', views.post_detail, name='post-detail'),
    path('add-reply/<post_id>', views.add_reply, name='add-reply'),
]

classApp/quiz/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url

app_name = 'quiz'

urlpatterns = [
    path('create-quiz/', views.create_quiz, name='create-quiz'),
    path('quiz-home/', views.quiz_home, name='quiz-home'),
    path('quiz/<quiz_id>', views.quiz_detail, name='quiz-detail'),
    path('add-ques/<quiz_id>', views.add_question, name='add-question'),
    path('attempt-quiz/<quiz_id>', views.attempt_quiz, name='attempt-quiz'),
    # path('view-result/<quiz_id>', views.attempt_quiz, name='view-result'),
]

classApp/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url

app_name = 'users'

urlpatterns = [
    path("", views.index_view, name='home'),
    path('student_register/',views.stud_register.as_view(),name='student_register'),
    path('teacher_register/',views.teacher_register.as_view(),name='teacher_register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('student-profile/', views.student_profile, name='student-profile'),
    path('teacher-profile/', views.teacher_profile, name='teacher-profile'),
    path('quiz-responses/<quiz_id>', views.quiz_responses, name='quiz_responses'),
    path('view-response-sheet/<resp_id>', views.view_response_sheet, name='view_response_sheet'),
]

classApp/discuss/models.py
from django.db import models
from users.models import User
from django.utils.timezone import now
from django.urls import reverse

class Post(models.Model):
    user1 = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    post_id = models.AutoField
    #slug = models.SlugField(unique=True)
    post_content = models.TextField()
    timestamp= models.DateTimeField(default=now)
    image = models.ImageField(upload_to="images",default="")

    def get_absolute_url(self):
        #id_str = ""+self.post_id
        return reverse("discuss:post-detail", kwargs={
            'post_id' : self.id
        })
    def get_reply_item_url(self):
        return reverse("discuss:add-reply", kwargs={
            'post_id' : self.id 
        })
    
class Replie(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    reply_id = models.AutoField
    reply_content = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default='')
    timestamp= models.DateTimeField(default=now)
    image = models.ImageField(upload_to="images",default="")

classApp/discuss/forms.py
from django import forms
from django.db.models import fields
from .models import *

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('post_content',)

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Replie 
        fields = ('reply_content',)

classApp/discuss/views.py
from django.shortcuts import get_object_or_404, redirect, render
from users.models import *
from .models import *
from users.decorators import *
from .forms import *

@student_required
def create_post(request):
    if request.method == "POST":
        form = PostForm(request.POST)

        if form.is_valid():
            stud = get_object_or_404(Student, user=request.user)
            data = form.save(commit=False)
            data.user1 = request.user
            data.image = stud.student_profile_pic
            data.save()
            return redirect("discuss:forum-home")
    else:
        form = PostForm()
    return render(request, 'discuss/add_post.html', {"form":form})

def forum_home(request):
    return render(request, 'discuss/forum.html', context={'posts' : Post.objects.all().order_by("-timestamp")})

def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    #post = Post.objects.get(post_id=post_id)
    replies = Replie.objects.filter(post = post).order_by("-timestamp")
    context = {
        "replies" : replies,
        "post" : post,
    }
    return render(request, 'discuss/post_detail.html', context)

@student_required
def add_reply(request, post_id):
    if request.method == "POST":
        form = ReplyForm(request.POST)

        if form.is_valid():
            post = get_object_or_404(Post, id=post_id)
            stud = get_object_or_404(Student, user=request.user)
            data = form.save(commit=False)
            data.user = request.user
            data.post = post 
            data.image = stud.student_profile_pic
            data.save()
            return redirect("discuss:forum-home")
    else:
        form = ReplyForm()
    return render(request, 'discuss/add_reply.html', {"form" : form})



            

classApp/templates/discuss/add_post.html
{% extends 'discuss/basic.html' %}
{% load crispy_forms_tags %}
<!--{% block title %} Forum {% endblock %}
{% block homeactive %} active {% endblock homeactive %}-->
{% block content %}
<br><br>
<div id="login-box"; style="padding: 70px 0; text-align: center;">
    <div class="items">
      <h1>Add a post</h1>   <br><br>

      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            {{ form|crispy }}        <!--Prints out the form that we've passed. as_p will render our form in paragraph tags-->
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Post</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Back to home? <a class="ml-2" href="{% url 'discuss:forum-home' %}">Go back!</a>
        </small>
    </div>

</div>   
{% endblock content %}

classApp/templates/discuss/add_reply.html
{% extends 'discuss/basic.html' %}
{% load crispy_forms_tags %}
<!--{% block title %} Forum {% endblock %}
{% block homeactive %} active {% endblock homeactive %}-->
{% block content %}
<br><br>
<div id="login-box"; style="padding: 70px 0; text-align: center;">
    <div class="items">
      <h1>Add a reply</h1>   <br><br>

      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            {{ form|crispy }}        <!--Prints out the form that we've passed. as_p will render our form in paragraph tags-->
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Reply</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Back to home? <a class="ml-2" href="{% url 'discuss:forum-home' %}">Go back!</a>
        </small>
    </div>

</div>   
{% endblock content %}

classApp/templates/discuss/basic.html
{% load static %}

<!doctype html>

<html lang="en">
  <head>
    <style>
      html *
      {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif !important;
      }
    </style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href=" {% static 'discuss/block.css' %} "> 
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{% url 'discuss:forum-home' %}">Classroom</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% block homeactive %} {% endblock homeactive %} ">
        <a class="nav-link" href="{% url 'discuss:forum-home' %}">Home <span class="sr-only"></span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'quiz:quiz-home' %}">Quiz <span class="sr-only"></span></a>
      </li>
      {% if user.is_authenticated %}
<ul class="navbar-nav mr-2">
<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href='#' id="navbarDropdown" role="button" data-toggle="dropdown"> Welcome {{request.user}}</a>
<div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
          
      <li class="nav-item {% block profileactive %} {% endblock profileactive %}">
        {% if request.user.is_student %}
        <a class="nav-link" href="{%url 'users:student-profile'%}">Profile</a>
        {% else %}
        <a class="nav-link" href="{%url 'users:teacher-profile' %}">Profile</a>
        {% endif %}
      </li>
      <li class="nav-item">
        {% if request.user.is_teacher %}
        <a class="nav-link" href="{%url 'quiz:create-quiz' %}">New Quiz</a>
        {% endif %}
      </li>
        </div>
      </li>      
{% else %}
<ul class="navbar-nav mr-2">
  <li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href='#' id="navbarDropdown" role="button" data-toggle="dropdown"> Signup</a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'users:teacher_register' %}">Teacher</a>
            <a class="dropdown-item" href="{% url 'users:student_register' %}">Student</a>
  </div>
  
      <li class="nav-item {% block loginactive %} {% endblock loginactive %}">
        <a class="nav-link" href="{% url 'users:login' %}">Login</a>
      </li>
      {% endif %}

    </ul>
  </div>
</nav>
<br>
</body>
{% if messages %}                                             <!--code to print out the flash messages-->
{% for message in messages %}
     <div class="alert alert-{{ message.tags }}">
       <br><br>
          {{ message }}
     </div>
{% endfor %}
{% endif %}
{% block content %}{% endblock content%}

<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
 <!-- {% block js %} {% endblock %}-->
</html>

classApp/templates/discuss/forum.html
{% extends 'discuss/basic.html' %}
{% load crispy_forms_tags %}
<!--{% block title %} Forum {% endblock %}
{% block homeactive %} active {% endblock homeactive %}-->
{% block content %}
<div class="container my-4">
<div class="jumbotron">
    <h1 class="display-4">Classroom Discuss</h1>
    <p class="lead">Welcome to our discussion forum <br>
    <hr class="my-4">
    {% if user.is_authenticated %}
    {% if request.user.is_student %}
    <a class="btn btn-primary btn-lg" data-toggle="modal" href="{% url 'discuss:add-post' %}">Add post!</a>
    {% endif %}
    {% endif %}
    </div>
    {% for post in posts %}
    <div class="container-fluid mt-10">
      <div class="row">
          <div class="col-md-12">
              <div class="card mb-4">
                  <div class="card-header">
                      <div class="media flex-wrap w-100 align-items-center"> <img src="/media/{{post.image}}"
                              class="d-block ui-w-40 rounded-circle" alt="">
                          <div class="media-body ml-3"> <a href="#" data-abc="true">{{post.user1}}</a>
                          </div>
                          <div class="text-muted small ml-3">
                            <div class="px-4 pt-3">{{post.timestamp}} </div>
                          </div>
                      </div>
                  </div>         
                  <div class="card-body">
                      <p>{{post.post_content}}</p>
                  </div>
                  <div class="card-footer d-flex flex-wrap justify-content-between align-items-center px-0 pt-1 pb-3"> 
                    <a class="btn btn-primary btn-lg" data-toggle="modal" href="{{post.get_absolute_url}}">View</a>                 
                  </div>
              </div>
          </div>
      </div>
  </div>
  {% endfor %}

</div>

<!-- Modal 
<div class="modal fade" id="questions" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% if user.is_authenticated %}
        <div class="modal-body">
          <form action="/" method="POST"> {% csrf_token %}
          <div class="form-group">
            <label for="exampleFormControlTextarea1">Add a new post!</label>
            <textarea class="form-control" id="content" name="content" rows="3"></textarea>
          </div>
        </div>
        {% else %}
        <h3>Please Login to post</h3>
        {% endif %}
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Post</button>
        </div>
      </div>
    </div>
  </div> -->
  {% endblock content %}

classApp/templates/discuss/post_detail.html
{% extends 'discuss/basic.html' %}
{% load crispy_forms_tags %}
<!--{% block title %} Forum {% endblock %}
{% block homeactive %} active {% endblock homeactive %}-->
{% block content %}
<div class="container my-4">
<div class="jumbotron">
    <h1 class="display-4">Classroom Discuss</h1>
    <!--<p class="lead">Welcome to our discussion forum. You can post your question or any related queries by simply clicking on the add post button. <br> Thankyou and Have a nice day!!</p>
    <hr class="my-4">
    <p>You can also reply to others post by clicking on their post and replying them.</p>
      <a class="btn btn-primary btn-lg" data-toggle="modal" href="{% url 'discuss:add-post' %}">Add post!</a>-->
    </div>

    <div class="container-fluid mt-10">
      <div class="row">
          <div class="col-md-12">
              <div class="card mb-4">
                  <div class="card-header">
                      <div class="media flex-wrap w-100 align-items-center"> <img src="/media/{{post.image}}"
                              class="d-block ui-w-40 rounded-circle" alt="">
                          <div class="media-body ml-3"> <a href="#" data-abc="true">{{post.user1}}</a>
                          </div>
                          <div class="text-muted small ml-3">
                            <div class="px-4 pt-3">{{post.timestamp}} </div>
                          </div>
                      </div>
                  </div>         
                  <div class="card-body">
                      <p>{{post.post_content}}</p>
                  </div>
                  
                  <div class="card-footer d-flex flex-wrap justify-content-between align-items-center px-3 pt-0 pb-3">
                    {% if user.is_authenticated %}
                    {% if request.user.is_student %}
                    <a class="btn btn-primary btn-lg" data-toggle="modal" href="{{post.get_reply_item_url}}">Reply</a>
                    {% endif %}
                    {% endif %}
                </div>
              </div>
          </div>
      </div>
  </div>

</div>
{% for reply in replies %}
<br>
<div class="container">
<div class="media">
    <img class="mr-3 rounded-circle" src="/media/{{reply.image}}" alt="." width="30px" height="30px">
    <div class="media-body">
      <h4 class="mt-0">{{reply.user}}	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;  <span><small style="font-size: 13px;">({{reply.timestamp}})</small></span></h4>   
      <h5>{{reply.reply_content}}</h5>
    </div>
  </div>
</div>
{% endfor %}
<!-- Modal 
<div class="modal fade" id="questions" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% if user.is_authenticated %}
        <div class="modal-body">
          <form action="/" method="POST"> {% csrf_token %}
          <div class="form-group">
            <label for="exampleFormControlTextarea1">Add a new post!</label>
            <textarea class="form-control" id="content" name="content" rows="3"></textarea>
          </div>
        </div>
        {% else %}
        <h3>Please Login to post</h3>
        {% endif %}
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Post</button>
        </div>
      </div>
    </div>
  </div> -->
  {% endblock content %}