classApp/classApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import discuss

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('', include('discuss.urls')),
    path('',include('quiz.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classApp/discuss/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url

app_name = 'discuss'

urlpatterns = [
    path('create-post/', views.create_post, name='add-post'),
    path('forum/', views.forum_home, name='forum-home'),
    path('post/<post_id>', views.post_detail, name='post-detail'),
    path('add-reply/<post_id>', views.add_reply, name='add-reply'),
]

classApp/quiz/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url

app_name = 'quiz'

urlpatterns = [
    path('create-quiz/', views.create_quiz, name='create-quiz'),
    path('quiz-home/', views.quiz_home, name='quiz-home'),
    path('quiz/<quiz_id>', views.quiz_detail, name='quiz-detail'),
    path('add-ques/<quiz_id>', views.add_question, name='add-question'),
    path('attempt-quiz/<quiz_id>', views.attempt_quiz, name='attempt-quiz'),
    # path('view-result/<quiz_id>', views.attempt_quiz, name='view-result'),
]

classApp/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url

app_name = 'users'

urlpatterns = [
    path("", views.index_view, name='home'),
    path('student_register/',views.stud_register.as_view(),name='student_register'),
    path('teacher_register/',views.teacher_register.as_view(),name='teacher_register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('student-profile/', views.student_profile, name='student-profile'),
    path('teacher-profile/', views.teacher_profile, name='teacher-profile'),
    path('quiz-responses/<quiz_id>', views.quiz_responses, name='quiz_responses'),
    path('view-response-sheet/<resp_id>', views.view_response_sheet, name='view_response_sheet'),
]

classApp/quiz/models.py
from django.db import models
from users.models import Teacher, User
from django.utils.timezone import now
from django.urls import reverse

class Question(models.Model):
    ques_id = models.AutoField 
    desc = models.CharField(max_length=300)
    choice1 = models.CharField(max_length=40)
    choice2 = models.CharField(max_length=40)
    choice3 = models.CharField(max_length=40)
    choice4 = models.CharField(max_length=40)
    ans = models.CharField(max_length=1)

class Quiz(models.Model):
    quiz_id = models.AutoField
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=50)
    desc = models.CharField(max_length=300)
    questions = models.ManyToManyField(Question)
    is_saved = models.BooleanField(default=False)

    def __str__(self):
        return self.name 
    def get_absolute_url(self):
        return reverse("quiz:quiz-detail", kwargs={
            'quiz_id' : self.id 
        })
    def get_add_ques_url(self):
        return reverse("quiz:add-question", kwargs={
            'quiz_id' : self.id 
        })
    def get_attempt_url(self):
        return reverse("quiz:attempt-quiz", kwargs={
            'quiz_id' : self.id 
        })
    def get_responses_url(self):
        return reverse("users:quiz_responses", kwargs={
            'quiz_id' : self.id 
        })

class Response(models.Model):
    response_id = models.AutoField
    choice_picked = models.CharField(max_length=1)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

class ResponseSheet(models.Model):
    resp_id = models.AutoField
    student = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    responses = models.ManyToManyField(Response)
    score = models.IntegerField(default=0)
    correct = models.IntegerField(default=0)
    wrong = models.IntegerField(default=0)
    def __str__(self):
        return f"{self.quiz.name} of {self.id}"
    def get_response_sheet_url(self):
        return reverse("users:view_response_sheet", kwargs={
            'resp_id' : self.id 
        })

classApp/quiz/forms.py
from django import forms
from django.db.models import fields
from .models import *

class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ('name','desc',)

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('desc','choice1', 'choice2', 'choice3', 'choice4', 'ans')

classApp/quiz/views.py
from django.contrib.auth.decorators import login_required
#from django.core.checks import messages
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from users.models import *
from .models import *
from users.decorators import *
from .forms import *

@login_required
@teacher_required
def create_quiz(request):
    if request.method == "POST":
        form = QuizForm(request.POST)

        if form.is_valid():
            data = form.save(commit=False)
            data.author = request.user 
            data.save()
            return redirect("quiz:quiz-home")

    else:
        form = QuizForm()
    return render(request, 'quiz/create_quiz.html', {"form" : form})

def quiz_home(request):
    return render(request, 'quiz/quiz_home.html', context={'quizzes' : Quiz.objects.all()})

@login_required
@teacher_required
def quiz_detail(request, quiz_id):
    quiz = Quiz.objects.get(id = quiz_id)

    context = {
        "quiz" : quiz,
    }
    return render(request, 'quiz/quiz_detail.html', context)

@login_required
@teacher_required
def add_question(request, quiz_id):
    if request.method == "POST":
        form = QuestionForm(request.POST)

        if form.is_valid():
            quiz = get_object_or_404(Quiz, id=quiz_id)
            data = form.save(commit=False)
            data.save()
            quiz.questions.add(data)
            url = "quiz/"+str(quiz_id)
            return redirect(reverse("quiz:quiz-detail",kwargs={'quiz_id':str(quiz_id)}))
    else:
        form = QuestionForm()
    return render(request, 'quiz/add_question.html', {"form" : form})

@login_required 
@student_required
def attempt_quiz(request, quiz_id):
    quiz = get_object_or_404(Quiz, id=quiz_id)
    response_qs = ResponseSheet.objects.filter(student=request.user, quiz=quiz)
    if response_qs.exists():
        messages.info(request, 'You have already attempted the quiz')
        return redirect("quiz:quiz-home")
    if request.method == 'POST':
        # response_qs = ResponseSheet.objects.filter(student=request.user, quiz=quiz)
        # if response_qs.exists():
        #     messages.info(request, ' You have already attempted the quiz')
        #     return redirect("quiz:quiz-home")
        response_sheet = ResponseSheet.objects.create(student=request.user, quiz=quiz)
        questions = quiz.questions.all()
        score = 0
        total=0
        wrong=0
        correct=0
        for q in questions:
            response = Response.objects.create(question=q, choice_picked=request.POST.get(q.desc))
            #response = Response(question=q, choice_picked=request.POST.get(q.desc))
            response_sheet.responses.add(response)
            #response_sheet.save()
            total += 1
            #print(request.POST.get(q.desc))
            #print(q.ans)
            if q.ans == request.POST.get(q.desc):
                score += 10
                correct += 1
            else:
                wrong += 1
        percent = score/(total*10) * 100
        response_sheet.score = score
        response_sheet.correct = correct
        response_sheet.wrong = wrong
        response_sheet.save()
        context = {
            'score' : score,
            'correct' : correct,
            'wrong' : wrong,
            'percent' : percent,
            'total' : total,
            'responses' : response_sheet.responses,
        }
        return render(request, 'quiz/result.html', context)
    else:
        questions = quiz.questions.all()
        context = {
            'quiz' : quiz,
            'questions' : questions,
        }
        return render(request, 'quiz/attempt-quiz.html', context)

        

classApp/templates/quiz/add_question.html
{% extends 'discuss/basic.html' %}
{% load crispy_forms_tags %}
<!--{% block title %} Forum {% endblock %}
{% block homeactive %} active {% endblock homeactive %}-->
{% block content %}
<br><br>
<div id="login-box"; style="padding: 70px 0; text-align: center;">
    <div class="items">
      <h1>Add a question</h1>   <br><br>

      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            {{ form|crispy }}        <!--Prints out the form that we've passed. as_p will render our form in paragraph tags-->
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Add</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Back to home? <a class="ml-2" href="{% url 'discuss:forum-home' %}">Go back!</a>
        </small>
    </div>

</div>   
{% endblock content %}

classApp/templates/quiz/attempt-quiz.html
{% extends 'quiz/dependencies.html' %}
 
{% block content %}
{% load static %}
<div class="container "; style="padding: 70px 0;">
<h1>Attempting {{quiz.name}}</h1> <br>
  
 <!-- <form action="attempt_quiz/"+str({{quiz.quiz_id}}) method="POST"> -->
    <form action='' method="POST">
    {% csrf_token %}
    {% for q  in questions%}
    <div class="form-group">
      <label for="question">{{q.desc}}</label>
    </div>
    <div class="form-check">
        <div class="form-check">
            <input class="form-check-input" type="radio" name="{{q.desc}}" id="gridRadios1" value="a">
            <label class="form-check-label" for="gridRadios1">
                {{q.choice1}}
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" name="{{q.desc}}" id="gridRadios2" value="b">
            <label class="form-check-label" for="gridRadios2">
                {{q.choice2}}  
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" name="{{q.desc}}" id="gridRadios1" value="c">
            <label class="form-check-label" for="gridRadios1">
                {{q.choice3}}  
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" name="{{q.desc}}" id="gridRadios2" value="d">
            <label class="form-check-label" for="gridRadios2">
                {{q.choice4}}   
            </label>
        </div>
        <br>
    </div>    
    {% endfor %}
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
    <!-- {% block script %}
        <script>
 
            console.log('hello world')
            const timer=document.getElementById('displaytimer')
            console.log(timer.textContent)
            const inputtag = document.getElementById('timer')
 
            t=0
            setInterval(()=>{
                t+=1
                timer.innerHTML ="<b>Timer: " +t+" seconds</b>"
                inputtag.value = t
            },1000)
        </script>
    {% endblock script %} -->
 
</div>
{% endblock %}

classApp/templates/quiz/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{% block title %} {% endblock %}</title>
    {% block css %} 
    <style>
      .head1 {
    color: #FBAD30;
    font-size: 2rem;
    font-weight: bold;
    height: 50px;
  }

  .head2 {
    color: #EF4926;
    font-size: 2rem;
    font-weight: bold;
  }
    </style>
    {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="/"><span class="head1">Tech</span> <span class="head2">Classroom</span></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              {% if user.is_authenticated %}
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link" href="#">Welcome {{request.user}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'quiz:create-quiz' %}">Add Quiz</a>
                </li>
                  <!-- {% if user.is_superuser %}
                  <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                    <ul class="navbar-nav">
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Admin
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                          <li><a class="dropdown-item" href="/add_quiz/">Add Quiz</a></li>
                          <li><a class="dropdown-item" href="/add_question/">Add Questions</a></li>
                          <li><a class="dropdown-item" href="/results/">Results of the Users</a></li>
                        </ul>
                      </li>
                    </ul>
                  </div>
                  {% endif %}
              </ul>
              {% else %} -->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="#">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Login</a>
              </li>
            </ul>
            <!-- {% endif %} -->
          </div>
        </div>
      </nav>
      {% block body %} {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
      {% block js %}{% endblock %}
</html>

classApp/templates/quiz/create_quiz.html
{% extends 'discuss/basic.html' %}
{% load crispy_forms_tags %}
<!--{% block title %} Forum {% endblock %}
{% block homeactive %} active {% endblock homeactive %}-->
{% block content %}
<br><br>
<div id="login-box"; style="padding: 70px 0; text-align: center;">
    <div class="items">
      <h1>Start a Quiz</h1>   <br><br>

      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            {{ form|crispy }}        <!--Prints out the form that we've passed. as_p will render our form in paragraph tags-->
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Create</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Back to home? <a class="ml-2" href="{% url 'discuss:forum-home' %}">Go back!</a>
        </small>
    </div>

</div>   
{% endblock content %}

classApp/templates/quiz/dependencies.html
{% load static %}
<html>
    <head>
        <title>
            Quiz 
        </title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    </head>
    <body>        
        {% include 'quiz/navbar.html' %}
        {% block content %}   
        {% endblock %}
        <br>
       
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    </body>
</html>

classApp/templates/quiz/navbar.html
{% load static %}
 
<style>
  .greet{
    font-size: 18px;
    color: #fff;
    margin-right: 20px;
  }
</style>
 
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
 
    <ul class="navbar-nav">
      
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'users:home' %}">Home</a>
      </li>
      </li>
      <li class="nav-item active">
        
      <!-- {% if request.user.is_staff %}
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'addQuestion' %}">Add Question</a>
      </li>
      {% endif %}  -->
 
      <!-- </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:login' %}">Login</a>
      </li> -->
    </ul>
  </div>
 
  <span class="greet">Hello, {{request.user}}</span>
  <span ><a  class="greet" href="{% url 'users:logout' %}">Logout</a></span>
 
</nav>

classApp/templates/quiz/quiz_detail.html
{% extends 'discuss/basic.html' %}
{% load crispy_forms_tags %}
<!--{% block title %} Forum {% endblock %}
{% block homeactive %} active {% endblock homeactive %}-->
{% block content %}
<div class="container my-4">
<div class="jumbotron">
    <h1 class="display-4">Quizzes</h1>
    <!--<p class="lead">Welcome to our discussion forum. You can post your question or any related queries by simply clicking on the add post button. <br> Thankyou and Have a nice day!!</p>
    <hr class="my-4">
    <p>You can also reply to others post by clicking on their post and replying them.</p>
      <a class="btn btn-primary btn-lg" data-toggle="modal" href="{% url 'discuss:add-post' %}">Add post!</a>-->
    </div>

    <div class="container-fluid mt-10">
      <div class="row">
          <div class="col-md-12">
              <div class="card mb-4">
                  <div class="card-header">
                      <div class="media flex-wrap w-100 align-items-center">
                          <h1>{{quiz.name}}</h1> 
                          <div class="media-body ml-3"> <a href="#" data-abc="true">{{quiz.author}}</a>
                          </div>
                          <!-- <div class="text-muted small ml-3">
                            <div class="px-4 pt-3">{{quiz.timestamp}} </div>
                          </div> -->
                      </div>
                  </div>         
                  <div class="card-body">
                      <p>{{quiz.desc}}</p>
                  </div>
                  <div class="card-footer d-flex flex-wrap justify-content-between align-items-center px-3 pt-0 pb-3">

                    <a class="btn btn-primary btn-lg" data-toggle="modal" href="{{quiz.get_add_ques_url}}">Add Question</a>
                </div>
              </div>
          </div>
      </div>
  </div>

</div>
{% for question in quiz.questions.all %}
<br>
<div class="container">
<div class="media">
    <div class="media-body">
        <h5>{{question.desc}}</h5>
        <ol>
            <li>{{question.choice1}}</li>
            <li>{{question.choice2}}</li>
            <li>{{question.choice3}}</li>
            <li>{{question.choice4}}</li>
        </ol>
    </div>
  </div>
</div>
{% endfor %}
<!-- Modal 
<div class="modal fade" id="questions" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% if user.is_authenticated %}
        <div class="modal-body">
          <form action="/" method="POST"> {% csrf_token %}
          <div class="form-group">
            <label for="exampleFormControlTextarea1">Add a new post!</label>
            <textarea class="form-control" id="content" name="content" rows="3"></textarea>
          </div>
        </div>
        {% else %}
        <h3>Please Login to post</h3>
        {% endif %}
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Post</button>
        </div>
      </div>
    </div>
  </div> -->
  {% endblock content %}

classApp/templates/quiz/quiz_home.html
{% extends 'discuss/basic.html' %}
{% load crispy_forms_tags %}
<!--{% block title %} Forum {% endblock %}
{% block homeactive %} active {% endblock homeactive %}-->
{% block content %}
<div class="container my-4">
    <div class="jumbotron">
        <h1 class="display-4">All Quizzes</h1>
        <!--<p class="lead">Welcome to our discussion forum. You can post your question or any related queries by simply clicking on the add post button. <br> Thankyou and Have a nice day!!</p>
        <hr class="my-4">
        <p>You can also reply to others post by clicking on their post and replying them.</p>
          <a class="btn btn-primary btn-lg" data-toggle="modal" href="{% url 'discuss:add-post' %}">Add post!</a>-->
        </div>
    <!--
        <div class="container-fluid mt-10">
          <div class="row">
              <div class="col-md-12">
                  <div class="card mb-4">
                      <div class="card-header">
                          <div class="media flex-wrap w-100 align-items-center"> 
                              email : {{teacher.email}} <br>
                              designation : {{teacher.designation}} <br>
    
                    </div>
                  </div>
              </div>
          </div>
      </div> -->
<!-- cards -->
<div class="container">
    <div class="container mx-auto mt-2">
      <div class="row">
  
        {% for quiz in quizzes %}
        <div class="col-md-4">
          <div class="card" style="width: 21rem;">
            <div class="card-body">
              <h5 class="card-title" style="text-align: center;">{{quiz.name}}</h5>
              <br>
              <p class="card-text">{{quiz.desc}}</p>
  
              {% if request.user.is_authenticated %}
              {% if request.user.is_teacher %}
              <div class="card-footer d-flex flex-wrap justify-content-between align-items-center px-0 pt-1 pb-3"> 
                  <a class="btn btn-primary btn-lg" data-toggle="modal" href="{{quiz.get_absolute_url}}">View</a>                 
              </div>
              {% else %}
              <div class="card-footer d-flex flex-wrap justify-content-between align-items-center px-0 pt-1 pb-3"> 
                  <a class="btn btn-primary btn-lg" data-toggle="modal" href="{{quiz.get_attempt_url}}">Attempt</a>                 
              </div>
              {% endif %}
              {% endif %}
              <br>
              <!-- <button data-bs-target="#exampleModal" data-bs-toggle="modal" data-time="{{i.time}}"
                data-questions="{{i.number_of_questions}}" data-name="{{i.name}}" data-id="{{i.id}}" id="btn"
                style="justify-content: center;" class="attempt btn mr-2 modal-button"><i class="fas fa-link"></i>Attempt
                Quiz</button> -->
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock content %}

classApp/templates/quiz/result.html
{% extends 'quiz/dependencies.html' %}
 
{% block content %}
{% for response in responses.all %}
<br>
<div class="container">
<div class="media">
    <div class="media-body">
        <h5>{{response.question.desc}}</h5>
        <ol>
            <li>{{response.question.choice1}}</li>
            <li>{{response.question.choice2}}</li>
            <li>{{response.question.choice3}}</li>
            <li>{{response.question.choice4}}</li>
        </ol>
        Response recorded: {{response.choice_picked}} <br>
        Correct answer:  {{response.question.ans}} 
    </div>
  </div>
</div>
{% endfor %}

<div class="container ">
        
    <div class="card-columns" style="padding: 10px; margin: 20px;">
        <div class="card" align="centre " style="width: 32rem; border:5px black solid">
<!--            <img class="card-img-top" src="http://kmit.in/emagazine/wp-content/uploads/2018/02/karnataka-results.jpg" alt="Card image cap">-->
            <div class="card-body">
                <h5 class="card-title">Score: {{score}}</h5>
 
                <p class="card-text">Percentage: {{percent}}%</p>
                <p class="card-text">Correct answers: {{correct}}</p>
                <p class="card-text">Incorrect answers: {{wrong}}</p>
                <p class="card-text">Total questions: {{total}}</p>
                <h5>All the best for next quiz!</h5>
            </div>
        </div>
    </div>
 
</div>
 
{% endblock %}